name: Build

on:
  push:
    branches: 
      - develop 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
          with:
            go-version: '^1.14.4'
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: make deps

      - name: Build
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: rjio
          path: rjio
