name: Docker Image CI

on:
  push:
    branches: 
      - develop
      - master 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag rjio
      - name: Docker Publish
        uses: manusa/actions-publish-docker@v1.0.1
        with:
          # Name of the Docker image
          name: rjio
          # Username for Docker registry
          username: ${{ secrets.dockerhub_username }}
          # Password for Docker registry
          password: ${{ secrets.dockerhub_password }}
