name: "Release"

on:
  push:
    tags:
      - "release/v*"

jobs:
  release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - name: Prepare deps
        run: make deps
      - name: Build rjio binary
        run: make build
      - name: Build rjio-fetch binary
        run: make build
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag rjio
      - name: Publish to Dockerhub 
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: wiennat/rjio
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            dist/*